from . import account_analytic_line
from . import account_invoice_line
from . import account_invoice
from . import hr_employee
from . import product
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import stock_move
from . import stock_traceability
from . import work_order_category
from . import work_order_service
from . import work_order_line
from . import work_order_signature
from . import work_order_tag
from . import work_order_team
from . import work_order
